inmakes_movie_project/movie/movie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie_app.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inmakes_movie_project/movie/movie_app/urls.py
from django.urls import path

from movie_app import views
app_name='movie_app'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name="detail"),
    path('add/',views.add_movie,name="add_movie"),
    path('edit/<int:id>/',views.update,name="update"),
    path('delete/<int:id>/',views.delete,name="delete"),
]

inmakes_movie_project/movie/movie_app/models.py
from django.db import models


# Create your models here.
class movie_details(models.Model):
    movie_name=models.CharField(max_length=250)
    movie_desc=models.TextField()
    year=models.IntegerField()
    Ticket_price=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.movie_name

inmakes_movie_project/movie/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie_details
from .form import FormMovies
# Create your views here.


def index(request):
    movie=movie_details.objects.all()
    context={
               'movie_list':movie
            }
    return render(request,'index.html',context)
def details(request,movie_id):
    movie=movie_details.objects.get(id=movie_id)
    return render(request,'details.html',{'movie':movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('movie_name')
        des=request.POST.get('movie_desc')
        Movie_year=request.POST.get('year')
        price=request.POST.get('Ticket_price')
        image=request.FILES['img']
        movie_db=movie_details(movie_name=name,movie_desc=des,year=Movie_year,Ticket_price=price,img=image)
        movie_db.save()
    return render(request,'add_movie.html')
def update(request,id):
    movies=movie_details.objects.get(id=id)
    form=FormMovies(request.POST or None, request.FILES, instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'movie':movies})
def delete(request,id):
    if request.method=='POST':
        movie=movie_details.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

inmakes_movie_project/movie/templates/add_movie.html
{% extends 'base.html' %}
{% block body %}

<form  method="post" enctype="multipart/form-data"style="text-align:center;">
    {% csrf_token %}
    <h1>ADD Movie Details</h1><br>

    <input type="text" name="movie_name" placeholder="Enter Movie Name"><br><br>
    <input type="text" name="movie_desc" placeholder="Enter Description"><br><br>
    <input type="text" name="year" placeholder="Enter Year"><br><br>
    <input type="text" name="Ticket_price" placeholder="Enter Ticket Price"><br><br>
    <input type="file" name="img" placeholder="Enter image"><br><br>
    <input type="submit"class="btn btn-success btn-lg" value="ADD">
    <a class="btn btn-warning btn-lg"  href="{% url 'movie_app:index'  %}">Cancel</a>

</form>
{% endblock %}

inmakes_movie_project/movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Movie Store</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css '%}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
        <a class="btn btn-primary btn-lg"  href="{% url 'movie_app:index'  %}">Home</a>
        <a class="btn btn-primary btn-lg"  href="{% url 'movie_app:add_movie'  %}">ADD</a>

  </a>
</nav>
<br>
{% block body %}
{% endblock %}
</body>
</html>

inmakes_movie_project/movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post"  style="text-align:center;">
      {% csrf_token %}
    <h2>Are You Want To Delete this Movie..</h2><br>
    <input type="submit" class="btn btn-danger btn-lg" value="Delete">
    <a class="btn btn-warning btn-lg"  href="{% url 'movie_app:index'  %}">Cancel</a>
</form>
{% endblock %}

inmakes_movie_project/movie/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h2>{{movie.movie_name}}<h2>
            <h6>{{movie.movie_desc}}</h6>
                <h6>Year: {{movie.year}}</h6>
                <h6>Ticket Price: {{movie.Ticket_price}}</h6>
                <a class="btn btn-primary btn-lg" href="{% url 'movie_app:update' movie.id %}" >UPDATE</a>
                <a class="btn btn-danger btn-lg" href="{% url 'movie_app:delete' movie.id %}">DELETE</a><br>
        </div>
    </div>
</div>
{% endblock %}

inmakes_movie_project/movie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" >
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="250px">
                  <div class="card-body">
                     <h5 class="card-title">{{i.movie_name}}</h5>
                        <a href="{% url 'movie_app:detail' i.id %}" class="btn btn-secondary">View Details</a>
                  </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}

inmakes_movie_project/movie/templates/update.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data" style="text-align:center;padding:12px;margin:8px;">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success btn-lg"value="Update">
</form>


{% endblock %}